baseurl         = "https://novartensemble.com"
theme           = "casper-two-ls"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls  = true

[params]
  title       = "<Collectif_Novart>"
  subtitle    = "Ensemble de Musique"
  copyright   = "© 2021"

  cover       = "img/logo2_rect.png"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["style.css"]
  RSSLink = ""


  fbName = "collectifnovart"
  githubName = "kontrabass2018"
  igName = "collectif.novart"
  mediumName = ""

  logo = ""
  orgName = "Collectif Novart"
  orgWebsite = "https://novartensemble.com"
  orgDescription = "Ensemble de Musique Novart S.E.N.C"

  showSupport = true

  author = "Leonardo"
  authorAvatar = "img/leonardo.jpg"
  authorLocation = "Montréal, QC, CAN"
  authorWebsite = "https://kontrabass2018.github.io"
  authorDescription = "Coder, Developer"

  pageNotFoundTitle = "404 - Page not found"

[taxonomies]
  tag = "tags"
  category = "categories"
  
[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Programmation 2021"
  url = "/categories/projet_2021"
  weight = 199


[[menu.main]]
  name = "Membres"
  url = "/categories/membre/"
  weight = 100


[[menu.main]]
  name = "Concerts"
  url = "/categories/concert"
  weight = 99

[[menu.main]]
  name = "Projets"
  url = "/categories/projet/"
  weight = 98

[[menu.main]]
  name = "Documents"
  url = "/categories/documents/"
  weight = 97